### ISSUE TITLE
Question about the right position to encode `retrieved`

### ISSUE THREAD

**Issue by soheeyang** [lucidrains/RETRO-pytorch#11]
Hi, I am currently reading through the code and got confused when I reached this line:

https://github.com/lucidrains/RETRO-pytorch/blob/92ff28755df53352547b1868fb03feae9931c1dd/retro_pytorch/retro_pytorch.py#L598

![image](https://user-images.githubusercontent.com/28291528/162612141-fa23d7f6-5835-4df7-bf81-6d2c27be7590.png)
According to Algorithm 1 in the [paper](https://arxiv.org/abs/2112.04426) (the screenshot above), doesn't this line need to go inside the decoder, under this line?
https://github.com/lucidrains/RETRO-pytorch/blob/92ff28755df53352547b1868fb03feae9931c1dd/retro_pytorch/retro_pytorch.py#L406

This is an example of how I think the code of `decoder.forward` should be.
```
def forward(self, x, *, context_mask = None, retrieved = None):
  encoded = False  # flag to know if p = min(P) (in the algorithm)
  ...
    if exists(cross_attn) and exists(retrieved):
      if not encoded:
        ...
        # use x (H at layer p where p = min(P)), not embed (Emb(X))
        x_as_context = repeat(x[:, :seq_index], 'b (k n) d -> (b k r) n d', n = self.chunk_size, r = num_neighbors)
        retrieved = self.encoder(retrieved, mask = encoder_retrieved_mask, chunked_seq = x_as_context)
        encoded = True
```

**Comment by lucidrains** [comment]
@soheeyang Hi Sohee again! Yet again you discovered another bug :( I apologize for this and have made a correction in the latest commit (v0.3.0) https://github.com/lucidrains/RETRO-pytorch/commit/4f99e316458fb13a5e4f881586f8436458cf4ead

**Comment by soheeyang** [comment]
@lucidrains Hi Phil, thank you so much for the prompt fix!
