### ISSUE TITLE
rotary embedding question

### ISSUE THREAD

**Issue by jinmang2** [lucidrains/RETRO-pytorch#12]
Hi! I have a two questions about the rotary embedding implementation.

## 1. Divide the d-dimension space in to d/2 sub-spaces
In rotary embedding, head_dim is divided by 2 to utilize the conjugate space with sin and cos. 

```python
from rotary_embedding_torch import RotaryEmbedding

head_dim = 64
rotary_emb = RotaryEmbedding(dim=head_dim)
```
```python
class RotaryEmbedding(nn.Module):
    def __init__(
        self,
        dim,
        custom_freqs = None,
        freqs_for = 'lang',
        theta = 10000,
        max_freq = 10,
        num_freqs = 1,
        learned_freq = False
    ):
        super().__init__()
        if exists(custom_freqs):
            freqs = custom_freqs
        elif freqs_for == 'lang':
            # freqs.shape == (head_dim // 2)
            freqs = 1. / (theta ** (torch.arange(0, dim, 2)[:(dim // 2)].float() / dim))
        ...
```

But the `freqs` of the rotary in RETRO is kind of weird. Rotary embedding in RETRO's Encoder and Decoder divides head_dim by 2 in advance and puts it as an input.

https://github.com/lucidrains/RETRO-pytorch/blob/4f99e316458fb13a5e4f881586f8436458cf4ead/retro_pytorch/retro_pytorch.py#L380-L381

And divide freq by 2 once again in the initializer as shown below.

https://github.com/lucidrains/RETRO-pytorch/blob/4f99e316458fb13a5e4f881586f8436458cf4ead/retro_pytorch/retro_pytorch.py#L92-L96

In this way, when `head_dim=42`, the shape of freqs is obtained as follows.
- In [rotary-embedding-torch](https://github.com/lucidrains/rotary-embedding-torch), `(head_dim // 2) is equal to (24,)`
- In [RETRO-pytorch](https://github.com/lucidrains/RETRO-pytorch), `(head_dim // 2 // 2) is equal to (12,)`

Because the `apply_rotary_emb` function concats the tensor that exceeds rot_dim, the shape of the resulting tensor is the same, but the rotary pos does not seem to be fully applied.

Hence, I think you need to modify the two lines of code as below.

- https://github.com/lucidrains/rotary-embedding-torch/blob/main/rotary_embedding_torch/rotary_embedding_torch.py#L76
    - The resulting tensor has the same shape.
```python
>>> ASIS
            freqs = 1. / (theta ** (torch.arange(0, dim, 2)[:(dim // 2)].float() / dim))
<<< TOBE
            freqs = 1. / (theta ** (torch.arange(0, dim, 2).float() / dim))
```
- https://github.com/lucidrains/RETRO-pytorch/blob/main/retro_pytorch/retro_pytorch.py#L95
    - As shown in the confirmation code below, the above modification is the same as the existing rotary embedding implementation.
    ```python
    import torch
    dim1 = hid_dim // n_heads
    dim2 = (hid_dim // n_heads) // 2
    freqs1 = 1. / (10000 ** (torch.arange(0, dim1, 2).float() / dim1))
    freqs2 = 1. / (10000 ** (torch.arange(0, dim2, 1).float() / dim2))
    assert torch.equal(freqs1, freqs2)
    ```
```python
>>> ASIS
        inv_freq = 1. / (10000 ** (torch.arange(0, dim, 2).float() / dim))
<<< TOBE
        inv_freq = 1. / (10000 ** (torch.arange(0, dim, 1).float() / dim))
```

## 2. rotate_half function
The `rotary_half` implementations of RETRO-pytorch and rotary-embedding-torch are slightly different.

```python
# In rotary-embedding-torch
# https://github.com/lucidrains/rotary-embedding-torch/blob/517ee2cfeb10602032ef9d282c19851e19dd8943/rotary_embedding_torch/rotary_embedding_torch.py#L34
def rotate_half(x):
    x = rearrange(x, '... (d r) -> ... d r', r = 2)
    x1, x2 = x.unbind(dim = -1)
    x = torch.stack((-x2, x1), dim = -1)
    return rearrange(x, '... d r -> ... (d r)')
```

```python
# In RETRO-pytorch
# https://github.com/lucidrains/RETRO-pytorch/blob/4f99e316458fb13a5e4f881586f8436458cf4ead/retro_pytorch/retro_pytorch.py#L104
def rotate_half(x):
    x = rearrange(x, '... (j d) -> ... j d', j = 2)
    x1, x2 = x.unbind(dim = -2)
    return torch.cat((-x2, x1), dim = -1)
```

In rotary, concat is stacked with `[0 1 0 1 0 1 0 1]`, and retro is stacked with `[0 0 0 0 1 1 1 1]`.
- `[0 0 0 0]` is pre-half
- `[1 1 1 1]` is post-half

I wonder why it was implemented with this change! (just curious)

Looking at your implementation, I am studying and matching the thesis. Thank you always :)

**Comment by jinmang2** [comment]
@lucidrains
If `1. Divide the d-dimension space in to d/2 sub-spaces` was the wrong implementation, would it be ok for me to put PR?

**Comment by lucidrains** [comment]
@jinmang2 oh hey! yes, sorry the logic wasn't quite correct, fixed in https://github.com/lucidrains/RETRO-pytorch/commit/f2d28157d3e3fbf07f3e3329d4cb17c0a1c53855

so this was actually a discovery by [EleutherAI](https://www.eleuther.ai/) and the building of [GPT-J](https://github.com/kingoflolz/mesh-transformer-jax) by Wang & Komatsuzaki et al. They found out that only rotating a part of the head dimension (and leaving the rest unrotated) leads to even better performance. I believe Deepmind picked up this practice in their latest language model (Gopher or something else)

And yes, you are correct that rotary can be split two ways! But as long as they match up later, it doesn't matter (and I believe I have it matched up correctly, but do submit a PR if you find otherwise)

**Comment by jinmang2** [comment]
I thought that shaw's rpe was simply used in the retro, but I didn't know there was such an insight!
Thanks for the feedback :) issue closing

**Comment by lucidrains** [comment]
@jinmang2 rotary embeddings is the best type of relative positional encoding, if you do not need to extrapolate to sequence lengths longer than what was trained on. it was proven out in [PaLM](https://arxiv.org/abs/2204.02311)! enough said! :)
