### ISSUE TITLE
`doc_ids_memmap` shape

### ISSUE THREAD

**Issue by josephcappadona** [lucidrains/RETRO-pytorch#2]
https://github.com/lucidrains/RETRO-pytorch/blob/7d305379b72232c54262742d3f80326ed5fdac9e/retro_pytorch/retrieval.py#L138

Is there a reason `doc_ids_memmap` is shape `(max_docs, )`? Shouldn't it be `(max_chunks, )` since it's mapping chunks to doc ids?

**Comment by lucidrains** [comment]
@josephcappadona you are right! fixed in 0.1.6!

**Comment by josephcappadona** [comment]
Also, `max_docs` should be removed as a parameter from the call to `text_folder_to_chunks_` in `TrainingWrapper.__init__`:

```

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-5-3c7f459ac414> in <module>()
     13     max_index_memory_usage = '1m',
     14     current_memory_available = '1G',
---> 15     chunks_to_embeddings_batch_size = 64
     16 )

/usr/local/lib/python3.7/dist-packages/retro_pytorch/training.py in __init__(self, retro, chunk_size, documents_path, knn, glob, chunks_memmap_path, seqs_memmap_path, doc_ids_memmap_path, max_chunks, max_seqs, max_docs, knn_extra_neighbors, processed_stats_json_path, faiss_index_filename, **index_kwargs)
    163                 max_chunks = max_chunks,
    164                 max_seqs = max_seqs,
--> 165                 max_docs = max_docs
    166             )
    167         else:

TypeError: text_folder_to_chunks_() got an unexpected keyword argument 'max_docs'
```

Unless you want to add it back as a parameter `text_folder_to_chunks_` and add a condition to break when `max_docs` is reached, which I'm guessing was the initial intention of the argument.

**Comment by lucidrains** [comment]
@josephcappadona oh yes, my bad :pray:

**Comment by lucidrains** [comment]
@josephcappadona are you planning on training RETRO with knowledge graphs?

**Comment by josephcappadona** [comment]
@lucidrains Depends what you mean by knowledge graphs, but yes, probably something like that. I'm currently exploring some papers and datasets to figure out what might be interesting experiments to run. I'm currently especially intrigued by this paper: [Language Models as Zero-Shot Planners: Extracting Actionable Knowledge for Embodied Agents](https://arxiv.org/abs/2201.07207). But there are a few other directions I could see myself going.
