### ISSUE TITLE
'NoneType' object is not callable

### ISSUE THREAD

**Issue by f-guoqiang** [lucidrains/RETRO-pytorch#29]
when I run the example of "RETRO Datasets", there is a wrong aboubt TypeError:

Traceback (most recent call last):
  File "/home/fgq/all/RETRO/fuxian_2.py", line 58, in <module>
    retro = RETRO(
  File "/home/fgq/all/RETRO/retro_pytorch/retro_pytorch.py", line 507, in __init__
    self.encoder = Encoder(
  File "/home/fgq/all/RETRO/retro_pytorch/retro_pytorch.py", line 337, in __init__
    wrapper(Attention(dim = dim, dim_head = dim_head, heads = heads, dropout = attn_dropout, causal = causal)),
  File "/home/fgq/all/RETRO/retro_pytorch/retro_pytorch.py", line 73, in __init__
    self.norm = norm_klass(dim)
TypeError: 'NoneType' object is not callable

# code
save_memmap(
    './train.chunks.dat',
    np.int32(np.random.randint(0, 8192, size = (NUM_CHUNKS, CHUNK_SIZE + 1)))
)

- generate nearest neighbors for each chunk

save_memmap(
    './train.chunks.knn.dat',
    np.int32(np.random.randint(0, 1000, size = (NUM_CHUNKS, NUM_NEIGHBORS)))
)

-  generate seq data

save_memmap(
    './train.seq.dat',
    np.int32(np.random.randint(0, 128, size = (NUM_SEQS,)))
)

- instantiate dataset class
train_ds = RETRODataset(
    num_sequences = NUM_SEQS,
    num_chunks = NUM_CHUNKS,
    num_neighbors = NUM_NEIGHBORS,
    chunk_size = CHUNK_SIZE,
    seq_len = 2048,
    chunk_memmap_path = './train.chunks.dat',
    chunk_nn_memmap_path = './train.chunks.knn.dat',
    seq_memmap_path = './train.seq.dat'
)

**Comment by lucidrains** [comment]
@f-guoqiang https://github.com/lucidrains/RETRO-pytorch/commit/96ade1f032265d7392e09c354c73614648d61546 this should resolve it!
