### ISSUE TITLE
Model training

### ISSUE THREAD

**Issue by malteos** [lucidrains/RETRO-pytorch#4]
Thanks for your awesome work @lucidrains ! 

Are you aware of any efforts on reproducing the actual model training?

**Comment by malteos** [comment]
Glad to hear that. I'd be happy to contribute. Are there any particular issues that need some help?

**Comment by lucidrains** [comment]
best to reach out to Eric, as he is doing the training :)

**Comment by lucidrains** [comment]
@malteos best to reach out to Erik, as he is doing the training ;)

**Comment by paraschopra** [comment]
maybe you can collaborate with elutherai. having a large (7b) open source
model with a huge index powered by retro will be awesome.

Regards,
Paras Chopra
@paraschopra <https://twitter.com/paraschopra> on twitter

**Comment by lucidrains** [comment]
@paraschopra Yup, someone at Eleuther is eyeing the paper (and probably going to use my repo) - so if Erik doesn't fall through, there's them

**Comment by ronald-d-rogers** [comment]
Do you all also plan on open sourcing world knowledge as well?

**Comment by lucidrains** [comment]
@ronald-d-rogers do you mean the retrieval database?

**Comment by ronald-d-rogers** [comment]
Yes, perhaps one for this new Pile?

**Comment by lucidrains** [comment]
@ronald-d-rogers I don't know what their specific plans are. Just ran into someone working close to the eleuther founders who was also working on retro

**Comment by lucidrains** [comment]
ok, i'm closing this, feel free to reach out to Erik or Kip (at Eleuther) if you are interested in contributing towards an open sourced model

**Comment by enijkamp** [comment]
@lucidrains Yes, working on retro-fitting CodeGen, but may take a few more weeks:
https://mobile.twitter.com/arankomatsuzaki/status/1508246117351362560

**Comment by ronald-d-rogers** [comment]
> @lucidrains Yes, working on retro-fitting CodeGen, but may take a few more weeks: https://mobile.twitter.com/arankomatsuzaki/status/1508246117351362560

@enijkamp I think what you all are doing is great. A difference between this and other models though is that it's a two part system, one is the model and the other is the retrieval database. Have y'all thought about whether or not you'd open source the retrieval database as well? My understanding is that it would be quite large (~93TB for MassiveText which is 10.5TB on disk, so maybe ~8TB for The Pile?).

**Comment by paraschopra** [comment]
@enijkamp great work with codegen. Looking forward to the open source version of RETRO.
