### ISSUE TITLE
Question: residual connect after `ChunkedCrossAttention`?

### ISSUE THREAD

**Issue by FutureWithoutEnding** [lucidrains/RETRO-pytorch#40]
In the end of `ChunkedCrossAttention`, output padding 0's:
https://github.com/lucidrains/RETRO-pytorch/blob/ab3c4a6f66341409b2b9105661682376355b4673/retro_pytorch/retro_pytorch.py#L295-L298

the comment saied ` will be added to the residual`， but 
the next is `ffn`，I don‘t find `residual connect`. (in Decoder forward):
https://github.com/lucidrains/RETRO-pytorch/blob/ab3c4a6f66341409b2b9105661682376355b4673/retro_pytorch/retro_pytorch.py#L441-L448

**Did i miss something?**

**Comment by lucidrains** [comment]
yea, you missed that the cross attention module was wrapped by a `PreNorm` module that includes the residual [here](https://github.com/lucidrains/RETRO-pytorch/blob/ab3c4a6f66341409b2b9105661682376355b4673/retro_pytorch/retro_pytorch.py#L76)

**Comment by FutureWithoutEnding** [comment]
Yes, I find it. Thanks.

**Comment by FutureWithoutEnding** [comment]
The `dim_head` in `RETRO __init__`, don't pass to Encoder and Decoder?

**Comment by FutureWithoutEnding** [comment]
And `norm_klass` variable is the meaning of `norm class`? or else?

**Comment by lucidrains** [comment]
@FutureWithoutEnding ah yes, you are right

fixed the `dim_head` not being passed

`norm_klass` is either layernorm or gated rmsnorm. class is a reserved word in python, so out of habit, usually spell it `klass` in software engineering
