### ISSUE TITLE
Confusions about cross attentions in encoder and decoder

### ISSUE THREAD

**Issue by itsucks** [lucidrains/RETRO-pytorch#6]
Hi, thanks for this wonderful repo. But I got confusions about the cross attention modules in encoder and decoder.
In retro_pytorch.py
`
has_cross_attn = not exists(cross_attn_layers) or layer_num in cross_attn_layers
` 
at line 272 and
`
has_cross_attn = not exists(cross_attn_layers) or layer_num in cross_attn_layers
`
at line 321, when cross_attn_layers is None, it'll introduce extra attention ops in encoder and unused corss attention modules in decoder. Is this a bug? Or did i miss something?
In my understanding, it should be
`
has_cross_attn = exists(cross_attn_layers) and (ayer_num in cross_attn_layers)
`
Am I right?

**Comment by lucidrains** [comment]
@itsucks thank you! so the logic i was going for was to always have cross attention layers on all layers, unless if one were to specify the specific layer numbers as in https://github.com/lucidrains/RETRO-pytorch/blob/main/retro_pytorch/retro_pytorch.py#L370

but i can see how that is confusing 😓
