### ISSUE TITLE
Confusions about cross attentions in encoder

### ISSUE THREAD

**Issue by Hi-archers** [lucidrains/RETRO-pytorch#7]
In your code 
https://github.com/lucidrains/RETRO-pytorch/blob/5260d70fae085ed0cc5cbe3e2d1b35947fee475d/retro_pytorch/retro_pytorch.py#L115-L119

When this class is called by Encoder, the x means retrieved chunks. In attentional mechanisms it produces q matrix, but i think it should produce k,v matrix. In encoder input sequence just lead us to make attention in retrieved chunks word.

https://github.com/lucidrains/RETRO-pytorch/blob/5260d70fae085ed0cc5cbe3e2d1b35947fee475d/retro_pytorch/retro_pytorch.py#L288-L294

**Comment by lucidrains** [comment]
hello!

<img width="655" alt="Screen Shot 2022-03-05 at 7 46 18 AM" src="https://user-images.githubusercontent.com/108653/156890410-316c4037-cb80-4d90-917c-f919e7201342.png">

yes, i believe it is correct to feed the retrieved chunks into the encoder, where by they look at the original sequence chunks to better modulate their representation, before being CCA-ed as key / values in the decoder

**Comment by lucidrains** [comment]
so basically in the encoder, the retrieved chunks are the queries, in the decoder, they are the key / values
